name: Build PSIs
on: release
jobs:
  Build-WIN:
    runs-on: windows-latest
    steps:
      - name: Install PKG
        run: npm install -g pkg
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Install Modules
        run: npm install
      - name: Build PSI Image
        run: pkg . --output server.exe --compress GZip && ren server.exe server.psi
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: server.psi
          asset_name: server-win.psi
          tag: ${{ github.ref }}
          overwrite: true
          body: "Windows Server Binary"
  Build-OSX:
    runs-on: macos-latest
    steps:
      - name: Install PKG
        run: npm install -g pkg
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Install Modules
        run: npm install
      - name: Build PSI Image
        run: pkg . --output server.psi --compress GZip
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: server.psi
          asset_name: server-osx.psi
          tag: ${{ github.ref }}
          overwrite: true
          body: "OSX Server Binary"
