name: BuildPSI
on: release
jobs:
  build-WIN:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Build
        run: npm run build-psi-windows
