name: BuildPSI
on:
  push:
    branches:
      - dev
  jobs:
    build:
      runs-on: windows-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            ref: my-branch
        - name: Build
          run: npm run build-psi-windows
